// Code generated by proto-gen-validator. DO NOT EDIT.
// source: github.com/lack-io/vine-example/validator/proto/validator.proto

package validator

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

import (
	errors "errors"
	is "github.com/lack-io/vine/util/is"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ is.Empty
var _ strings.Builder
var _ = errors.New("")

func (m *Validate) Validate() error {
	errs := make([]error, 0)
	if is.Zero(m.Uint32) {
		errs = append(errs, errors.New("field 'uint32' is required"))
	}
	return is.MargeErr(errs...)
}

func (m *Enum) Validate() error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}
